- name: Install Docker and Docker-Compose
  become: yes
  pacman:
    name:
      - docker
      - docker-compose

- name: Enable Docker Daemon
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    group: docker
    append: yes
