- name: Install arc-gtk-theme
  become: yes
  pacman:
    name:
      - arc-gtk-theme

- name: Compton
  become: yes
  pacman:
    name:
      - compton

- name: Dunst
  become: yes
  pacman:
    name:
      - dunst
