- name: Install Xorg and tools
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit

- name: Install i3 Gaps
  become: yes
  pacman:
    name: i3-gaps

- name: Install status bar
  yay:
    name: polybar

- name: Install screen utilities
  become: yes
  pacman:
    name:
      - arandr
      - i3lock
      - scrot
      - feh
      - light
      - lxappearance
      - lxrandr
