- name: Install image tools
  yay: name={{ item }}
  loop:
    - exiv2
    - perl-image-exiftool
    - libvips
    - imagemagick
    - gocr

- name: Install image viewer
  become: yes
  pacman: name=sxiv
