- name: Install ZSH
  become: yes
  pacman:
    name: zsh

- name: Set ZSH as user's shell
  become: yes
  shell: chsh -s /bin/zsh phakiller

- name: Install Termite
  become: yes
  pacman:
    name: termite

- name: Check oh-my-zsh installation
  stat: 
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  changed_when: False

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: oh_my_zsh.stat.exists == False
